import fs from "fs";
import path from "path";
import { sync as globSync } from "glob";
import reactDocgen from "react-docgen-typescript";

// Output folder
const outPath = path.join(process.cwd(), "src", "generated");
if (!fs.existsSync(outPath)) fs.mkdirSync(outPath, { recursive: true });

// Configure parser
const parser = reactDocgen.withDefaultConfig({
  propFilter: (prop) => {
    if (prop.parent && prop.parent.fileName.includes("node_modules")) return false;
    return true;
  },
});

// Gather all component files
const files = globSync("src/components/**/*.tsx", { cwd: process.cwd(), absolute: true })
  .filter((f) => !f.includes("PrintTemplate")); // skip templates

// Parse components
const docs = files.reduce((acc, file) => {
  try {
    const components = parser.parse(file);
    acc[path.relative(process.cwd(), file)] = components;
  } catch (e) {
    console.warn("Failed to parse", file, e.message);
    acc[path.relative(process.cwd(), file)] = [];
  }
  return acc;
}, {}); // ✅ only this line, remove the TS type assertion

// Generate Markdown files
for (const [file, components] of Object.entries(docs)) {
  if (!components.length) {
    const md = `# ${path.basename(file, ".tsx")}\n\n` +
      `File: \`${file}\`\n\n` +
      "_No props defined for this component._\n";
    fs.writeFileSync(path.join(outPath, `${path.basename(file, ".tsx")}.md`), md, "utf-8");
    continue;
  }

  components.forEach((component) => {
    let md = `# ${component.displayName}\n\n`;
    md += `File: \`${file}\`\n\n`;
    if (component.description) md += `${component.description}\n\n`;

    if (component.props && Object.keys(component.props).length) {
      md += `## Props\n\n| Name | Type | Default | Description |\n|------|------|---------|-------------|\n`;
      Object.entries(component.props).forEach(([name, prop]) => {
        md += `| ${name} | \`${prop.type.name}\` | ${prop.defaultValue?.value || ""} | ${prop.description || ""} |\n`;
      });
    } else {
      md += "_No props defined for this component._\n";
    }

    fs.writeFileSync(path.join(outPath, `${component.displayName}.md`), md, "utf-8");
  });
}

// Write JS module exporting the raw data
fs.writeFileSync(
  path.join(outPath, "docs.js"),
  `// Auto-generated by scripts/generate-docs.js\nexport default ${JSON.stringify(docs, null, 2)};\n`,
  "utf-8"
);

console.log("Documentation generated:", Object.keys(docs).length, "components");